# From 'infra-ansible'
- src: https://github.com/redhat-cop/infra-ansible
  version: v1.0.11
# Personal role for handling virtualization
- src: https://github.com/bvkin/config-libvirt.git
# Personal for handling host files on machines
- src: https://github.com/bvkin/config-hosts-file
