# From 'infra-ansible'
- src: https://github.com/bvkin/config-hosts-file
- src: https://github.com/redhat-cop/infra-ansible
  version: v1.0.11
- src: https://github.com/stackhpc/ansible-role-libvirt-vm.git
  version: v1.6.0
