# From 'infra-ansible'
- src: https://github.com/redhat-cop/infra-ansible
  version: v1.0.11
# Role for configuring nfs
- src: https://github.com/geerlingguy/ansible-role-nfs.git
  version: 1.5.0
# Configuration for iscsi
- src: https://github.com/bvkin/ansible.targetcli.git
# Personal role for handling virtualization
- src: https://github.com/bvkin/config-libvirt-vms.git
# Personal role for handling components for aiding in virtualization
- src: https://github.com/bvkin/config-libvirt-components.git
# Personal for handling host files on machines
- src: https://github.com/bvkin/config-hosts-file
