---

- hosts: localhost
  vars:
    vundle_path: "{{ lookup('env','HOME') }}/.dotfiles/vim/bundle"  
  tasks:
    - name: Ensure vim is installed
      package:
        name: vim 
        state: present

    - name: Remove old .vimrc file
      file: 
        path: ~/.vimrc
        state: absent

    - name: Link desired .vimrc file
      file:
        src: "{{ lookup('env','HOME') }}/.dotfiles/vim/{{ dotfiles.vim.rc_file }}"
        dest: "{{ lookup('env','HOME') }}/.vimrc"
        state: link

    - name: Ensure vundle path exists
      file:
        path: "{{ vundle_path }}"
        state: directory
        recurse: True

    - name: Add vundle
      git: 
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{ vundle_path }}/Vundle.vim"

    - name: Pull in dependancies
      copy: 
        src: "{{ inventory_dir }}/../files/{{ item }}"
        dest: "{{ lookup('env','HOME') }}/.dotfiles/vim/"
      with_items:
        - "{{ dotfiles.vim.modules }}"

