---


libvirt_vms:
  - state: present
    name: 'tst'
    memory_mb: 512
    vcpus: 1
    format: "qcow2"
    volumes:
      - name: "tst-run.qcow2"
        device: "disk"
        format: "qcow2"
        capacity: "9GB"
        pool: "default"
        image: "/home/bkincaid/libvirt/qcow-test/tst.qcow2"
      - name: "tst-config.iso"
        device: "disk"
        format: "raw"
        capacity: "1MB"
        pool: "default"
        image: "/home/bkincaid/libvirt/qcow-test/config.iso"
